### PR TITLE
PKS cluster support

### PR DESCRIPTION
**Pull request by scothis**
Run FATS against a pre-provisioned PKS cluster.

This will require that we limit the concurrency of FATS jobs on travis to 1, since concurrent PKS builds will collide and cause failures and potentially corrupt the cluster preventing future jobs from passing until manually fixed.

In the future, we can provision a PKS cluster per run.

Refs #15

### CODE REVIEW

**Comment by scothis** [comment]
It's possible for the tests to pass https://travis-ci.org/projectriff/fats/jobs/450656535

**Comment by scothis** [comment]
> what has motivated the introduction of a non-default namespace?

There are namespace resources that `riff system uninstall` leaves behind that will cause issues with subsequent runs.  By pushing all work into a unique namespace that we can delete after the test run, each run will be cleaner, not clean, but cleaner.

> the PKS cluster is the same across Travis runs, is that right? no way to work around the creation time penalty on Travis CI? or are there other reasons?

Our goal is to eventually provision a PKS cluster per run. I don't like reusing clusters because there are cluster scoped resources that could leak between runs, moreover, we can only have a single concurrent run without causing serious side effects.

Depending on how many other environments we test against, there is a point were it will be faster to provision a new cluster and wait for the slow provision time in parallel than to serialize each job.

**Comment by glyn** [comment]
Merged as b5ad68c7d5673c57529403a2f7a633113a97394f.

@fbiville this PR was blocking progress on some other fats work, so we decided to merge it now and apply any other fixes later.

**Comment by fbiville** [comment]
No problem :)

**Pull request closed without merging**
