### PR TITLE
adding azure templates

### PR DESCRIPTION
**Pull request by sbawaska**
creating templates for some fats tasks, so that they can be easily
called from azure pipelines.

### CODE REVIEW

**Comment by jldec** [comment]
how about using bash scripts instead of ci-specific "templates"?

**Comment by scothis** [comment]
> how about using bash scripts instead of ci-specific "templates"?

That's that status quo for FATS.

**Comment by sbawaska** [comment]
@scothis The variables defined in the pipeline.yml are available as environment variables. From https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch

```
Notice that variables are also made available to scripts through environment variables. The syntax for using these environment variables depends on the scripting language. Name is upper-cased, . replaced with _, and automatically inserted into the process environment. Here are some examples:

Batch script: %VARIABLE_NAME%
PowerShell script: $env:VARIABLE_NAME
Bash script: $VARIABLE_NAME
```

I only added a minikube template because that was my immediate requirement to use in more than one repo. We could generalize it later.

**Comment by sbawaska** [comment]
@jldec all the heavy lifting is done in scripts. These templates are just trying to make consuming them easier.

**Comment by scothis** [comment]
@sbawaska cool, testing that out with https://github.com/projectriff/fats/pull/141

**Comment by sbawaska** [comment]
Since https://github.com/projectriff/fats/pull/141 fails, it looks like there is no way to have global secrets. closing for now.

**Pull request closed without merging**
