### PR TITLE
test streaming

### PR DESCRIPTION
**Pull request by sbawaska**
Adding a util function and macros to help with testing streaming functions.

### CODE REVIEW

**Comment by glyn** [comment]
`Run Tests/Run function fats-cluster-repeater-java` is failing with the same symptoms on kind and GKE (currently waiting for PKS results):
```
  fats-1574679131-gke/fats-cluster-repeaterceff41ffe873200852dd15273a69ee57-build-pod[build]: [INFO] Building jar: /workspace/target/repeater-0.1.0-SNAPSHOT.jar
  fats-1574679131-gke/fats-cluster-repeaterceff41ffe873200852dd15273a69ee57-build-pod[build]: [INFO] ------------------------------------------------------------------------
  fats-1574679131-gke/fats-cluster-repeaterceff41ffe873200852dd15273a69ee57-build-pod[build]: [INFO] BUILD SUCCESS
  fats-1574679131-gke/fats-cluster-repeaterceff41ffe873200852dd15273a69ee57-build-pod[build]: [INFO] ------------------------------------------------------------------------
  fats-1574679131-gke/fats-cluster-repeaterceff41ffe873200852dd15273a69ee57-build-pod[build]: [INFO] Total time:  20.981 s
  fats-1574679131-gke/fats-cluster-repeaterceff41ffe873200852dd15273a69ee57-build-pod[build]: [INFO] Finished at: 2019-11-25T11:17:26Z
  fats-1574679131-gke/fats-cluster-repeaterceff41ffe873200852dd15273a69ee57-build-pod[build]: [INFO] ------------------------------------------------------------------------
  fats-1574679131-gke/fats-cluster-repeaterceff41ffe873200852dd15273a69ee57-build-pod[build]:   Removing source code
  fats-1574679131-gke/fats-cluster-repeaterceff41ffe873200852dd15273a69ee57-build-pod[build]: 
  fats-1574679131-gke/fats-cluster-repeaterceff41ffe873200852dd15273a69ee57-build-pod[build]: Java Function Buildpack 0.2.0-BUILD-SNAPSHOT
  fats-1574679131-gke/fats-cluster-repeaterceff41ffe873200852dd15273a69ee57-build-pod[build]:   Java: Contributing to layer
  fats-1574679131-gke/fats-cluster-repeaterceff41ffe873200852dd15273a69ee57-build-pod[build]:     Writing SPRING_CLOUD_FUNCTION_LOCATION to launch
  fats-1574679131-gke/fats-cluster-repeaterceff41ffe873200852dd15273a69ee57-build-pod[build]:   riff Streaming HTTP Adapter 0.0.1: Contributing to layer
  fats-1574679131-gke/fats-cluster-repeaterceff41ffe873200852dd15273a69ee57-build-pod[build]:     Reusing cached download from buildpack
  fats-1574679131-gke/fats-cluster-repeaterceff41ffe873200852dd15273a69ee57-build-pod[build]:     Expanding to /layers/io.projectriff.java/streaming-http-adapter
  fats-1574679131-gke/fats-cluster-repeaterceff41ffe873200852dd15273a69ee57-build-pod[build]:   riff Java Invoker 0.2.0+snapshot: Contributing to layer
  fats-1574679131-gke/fats-cluster-repeaterceff41ffe873200852dd15273a69ee57-build-pod[build]:     Reusing cached download from buildpack
  fats-1574679131-gke/fats-cluster-repeaterceff41ffe873200852dd15273a69ee57-build-pod[build]:     Expanding to /layers/io.projectriff.java/riff-invoker-java
  fats-1574679131-gke/fats-cluster-repeaterceff41ffe873200852dd15273a69ee57-build-pod[build]:   Process types:
  actual_data: 
      ... etc. etc. for over 20 seconds ...
  actual_data: 
  Actual data not same as expected
  Actual:
  Expected:
  [foo foo]
  ##[error]Process completed with exit code 1.
```

**Comment by glyn** [comment]
Tried to reproduce the problem using a GKE cluster and executing the necessary commands one at a time. Unfortunately, it worked first time (produced "foo foo").

**Comment by glyn** [comment]
From the failing job's riff Streaming Runtime logs:
```
2019-11-25T11:16:48.724Z	ERROR	controller-runtime.controller	Reconciler error	{"controller": "processor", "request": "fats-1574679131-gke/fats-cluster-repeater-java", "error": "could not resolve an image"}
```
Unfortunately, this doesn't say which image caused the problem or what the specific issue in resolving the image was. It could be that the image doesn't exist, or is not accessible by the pod that's trying to use it, or something else.

**Comment by scothis** [comment]
While the streaming tests are still disabled, merging to provide support to upstream components that need to test the streaming runtime. It's likely that there are issues in those upstream components that will unlock the streaming tests here.

**Pull request merged**
